### ISSUE TITLE
v0.2.5: Improper comparison of python version

### ISSUE THREAD

**Issue by gdalmau** [eduardo-matos/django-global-permissions#20]
In the latest version 0.2.5 the python version is improperly compared in order to import `gettext_lazy` or `ugettext_lazy` https://github.com/eduardo-matos/django-global-permissions/blob/master/global_permissions/models.py#L9-L12

```python
if platform.python_version() >= '3.8':
    from django.utils.translation import gettext_lazy as _
else:
    from django.utils.translation import ugettext_lazy as 
```

This causes that python versions of `3.10` and above to have an improper comparison:

```python
>>> import platform
>>> platform.python_version()
'3.10.2'
>>> platform.python_version() >= '3.8'
False
```

**Comment by gdalmau** [comment]
@FernandoCelmer This results in running Django 4.0.3 on python 3.10 and above to not work with this library. I suggest that in order to import `gettext_lazy` or `ugettext_lazy` we compare the django version since `ugettext_lazy` was deprecated in django 4.0 and above

```python
import django
if django.get_version()[0] >= 4:
    from django.utils.translation import gettext_lazy as _
else:
    from django.utils.translation import ugettext_lazy as _
```

Another alternative is also to use `ImportError`:

```python
try:
    from django.utils.translation import gettext_lazy as _
except ImportError:
    from django.utils.translation import ugettext_lazy as _
```

**Comment by FernandoCelmer** [comment]
Thanks for the tips and bug alert! It was essential for the proper functioning of the package. @gdalmau
