### ISSUE TITLE
Changelog / tags for 0.2.5 and 0.2.6 

### ISSUE THREAD

**Issue by petrklus** [eduardo-matos/django-global-permissions#24]
Hi,

I can see on PyPi that there are two more versions available, however, there does not seem to be any information about them here in the repo.

Can you shed any light on this, please?

Looking at: https://pypi.org/project/django-global-permissions/#history

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/1115667/174625745-4310c4cc-5f97-40df-8843-60558f5e4b4f.png">

**Comment by FernandoCelmer** [comment]
Hello @petrklus. Follow the link with more information about the last two updates ([v0.2.5](https://github.com/eduardo-matos/django-global-permissions/releases/tag/0.2.5) and [v0.2.6](https://github.com/eduardo-matos/django-global-permissions/releases/tag/0.2.6)). Thanks for the question!

- https://github.com/eduardo-matos/django-global-permissions/releases/tag/0.2.6
- https://github.com/eduardo-matos/django-global-permissions/releases/tag/0.2.5
