### ISSUE TITLE
global_permissions not working for Django 1.7+

### ISSUE THREAD

**Issue by soerenbe** [eduardo-matos/django-global-permissions#5]
I currently try to get the library to run. I discovered 2 issues. I could reproduce the error in a plain Django installation:

```
~/tmp/perm/ptest$ pip install django django-global-permissions
...
~/tmp/perm/ptest$ pip list
argparse (1.2.1)
Django (1.8.7)
django-global-permissions (0.2.0)
pip (1.5.6)
setuptools (18.4)
wsgiref (0.1.2)
```

### Django builds a migration
```
~/tmp/perm/ptest$ ./manage.py makemigrations
Migrations for 'global_permissions':
  0001_initial.py:
    - Create proxy model GlobalPermission
```

This migration file should be shipped with the package. I am not sure why Django produce a migration for a Proxy Model. Maybe Django didn't do that in earlier versions.

### Django admin is not working

Running the 'runserver' and go to http://localhost:8000/admin/global_permissions/globalpermission/ produce a server error:

```
Request Method:	GET
Request URL:	http://localhost:8000/admin/global_permissions/globalpermission/
Django Version:	1.8.7
Exception Type:	AttributeError
Exception Value:	
'super' object has no attribute 'get_query_set'
Exception Location:	/home/zeus/tmp/perm/local/lib/python2.7/site-packages/global_permissions/models.py in get_queryset, line 12
Python Executable:	/home/zeus/tmp/perm/bin/python
```

**Comment by eduardo-matos** [comment]
Thanks for letting me know!

### Django builds a migration
I tried to simulate the first error in a fresh Django installation, but couldn't get the same result. Maybe you forgot to add `'django.contrib.contenttypes'` to `INSTALLED_APPS`.

![django-global-permissions-migrations](https://cloud.githubusercontent.com/assets/483681/11460310/0752827a-96d1-11e5-9048-6a64574eb70a.png)


### Django admin is not working
That's a bug! It's fixed on version [0.2.1](https://pypi.python.org/pypi/django-global-permissions/0.2.1).

**Comment by soerenbe** [comment]
Cool! This was fast. :-)

The Admininterface now working for me. But I still get the migrations on this proxy model:

![django_global_permissions](https://cloud.githubusercontent.com/assets/10573594/11467429/4ce93884-9748-11e5-947c-f4c17589d34e.png)

Maybe you forgot to add global_permissions? (I did that in one of my tests) This is what I exactly do:

```
virtualenv djp
source djp/bin/activate
pip install django-global-permissions
django-admin startproject p2
cd p2
./manage migrate
echo -e "INSTALLED_APPS += ('global_permissions',)\n" >> p2/settings.py
./manage.py migrate
```


I have a little different setup after virtualenv. ( I use Ubuntu 14.04). But I dont think this is a problem.
```
[russberg@russberg ] ~/tmp$ virtualenv djp
New python executable in djp/bin/python
Installing setuptools, pip...done.
1 [russberg@russberg ] ~/tmp$ source djp/bin/activate
(djp)[russberg@russberg ] ~/tmp$ pip list
argparse (1.2.1)
pip (1.5.4)
setuptools (2.2)
wsgiref (0.1.2)
(djp)[russberg@russberg ] ~/tmp$ pip install django-global-permissions > /dev/null
(djp)[russberg@russberg ] ~/tmp$ pip list
argparse (1.2.1)
Django (1.8.7)
django-global-permissions (0.2.1)
pip (1.5.4)
setuptools (2.2)
wsgiref (0.1.2)
(djp)[russberg@russberg ] ~/tmp$
```

**Comment by eduardo-matos** [comment]
You're right! I was not running the migration after installing `django-global-permissions`.
I've added a migration script to the build. Try upgrading to version [0.2.2](https://pypi.python.org/pypi/django-global-permissions/0.2.2).

**Comment by soerenbe** [comment]
Great!
Thanks for your effort.
