### ISSUE TITLE
Publish 0.2.3 to pip?

### ISSUE THREAD

**Issue by alexandernst** [eduardo-matos/django-global-permissions#6]
Can you publish the 0.2.3 to pip?

Current version there is 0.2.2 https://pypi.python.org/pypi/django-global-permissions

**Comment by eduardo-matos** [comment]
Sure.

I'll do it as soon as possible.
For now you can install directly from GitHub.

**Comment by SerhiyRomanov** [comment]
So, when do you can publish 0.2.3 to pip?

**Comment by eduardo-matos** [comment]
@SerhiyRomanov 
Sorry for being so late.
I've just done that!

https://pypi.python.org/pypi/django-global-permissions/0.2.3
